services:
  - type: web
    name: acemate-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key:sk_xd67gov7_VQ6TeXiK0zZLxWbTjH8lyvmP
        sync: false
      - key: ENDEE_URL
        value: http://endee-server:8080

  - type: web
    name: endee-server
    env: docker
    image: endeeio/endee-server:latest
    envVars:
      - key: NDD_NUM_THREADS
        value: "0"
      - key: NDD_AUTH_TOKEN
        value: ""
    disk:
      name: endee-data
      mountPath: /data
      sizeGB: 10
